added validation for needed programs.

diff --git a/exco b/exco
--- a/exco
+++ b/exco
@@ -1,5 +1,16 @@
 #!/bin/sh
 
+YELLOW="\033[1;33m"
+NC="\033[0m"
+
+programs=("tar" "bzip2" "gzip" "7z" "unrar" "rar" "zip")
+
+for prog in "${programs[@]}"; do
+  if ! command -v "$prog" &> /dev/null; then
+    echo -e "${YELLOW}WARNING${NC}: Command '$prog' not found!"
+  fi
+done
+
 extract() {
     ext="${1##*.}"
     if [ "$ext" = "tar" ]
